-------------------------------------------------data exploration

select * from INFORMATION_SCHEMA.TABLES;
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers';

-------------------------------------------------dim exploration
select distinct country from gold.dim_customers;
select distinct category,subcategory,product_name from gold.dim_products order by 1,2,3;

--------------------------------------------------date exploration
select min(order_date) as first,max(order_date) as last,
datediff(MONTH,min(order_date),max(order_date)) as range_years
from gold.fact_sales;

select min(birthdate) AS old,MAX(BIRTHDATE) AS young,
DATEDIFF(year,min(birthdate),getdate()) as oldage,
datediff(year,max(birthdate),getdate()) as youngage
FROM GOLD.dim_customers;
select * from gold.dim_customers;

-------------------------------------------------------------------------------measure exploration
select sum(sales_amount) as tottal from gold.fact_sales;-----total sales
--------find how many items are sold
select sum(sales_quantity) as total_quantity from gold.fact_sales;
-----------find avag selling price
select avg(sales_price) as avg_price from gold.fact_sales;
-------find tottal no of orders
select count(*) as orders  from gold.fact_sales; 
select count(distinct(order_number)) as orders  from gold.fact_sales; 
---------find no of products
select count(*) as products  from gold.dim_products; 
select count(distinct(product_name)) as orders  from gold.dim_products; 
---find no of customers
select count(*) as customers  from gold.dim_customers; 
select count(distinct(customer_id)) as customers  from gold.dim_customers; 
---------find no of cust that has placed an order
select count(distinct(customer_key)) as total_cust from gold.fact_sales; 
------------------------------------------------------------------------------------
--Generate a report that shows all key metrics of the business
select 'Total_sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total_quantity' as measure_name,sum(sales_quantity) as measure_value from gold.fact_sales
union all
select 'Avg_price' as measure_name,avg(sales_price) as measure_value from gold.fact_sales
union all
select 'Total_orders' as measure_name,count(distinct(order_number)) as measure_value  from gold.fact_sales
union all
select 'Total_products' as measure_name,count(distinct(product_name)) as measure_value  from gold.dim_products
union all
select 'Total_customers' as measure_name,count(distinct(customer_id)) as measure_value  from gold.dim_customers
union all
select 'Total_customers_orders' as measure_name,count(distinct(customer_key)) as measure_value from gold.fact_sales; 

--------------------------------Magnitude analysis
--find total customers by countries
select count(distinct(customer_id)) as customers,country from
gold.dim_customers group by country order by country desc;

---find total customers by gender
select count(distinct(customer_id)) as customers,gender from
gold.dim_customers group by gender;
---find total products by category
select count(distinct(product_name)) as products, category from gold.dim_products
group by category;
---what is the avg costs in each category
select avg(cost) as avg_cost,category from gold.dim_products
group by category;
--what is the total revenue generayed for each category
select sum(f.sales_amount) as total_revenue,p.category from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.category order by sum(f.sales_amount) desc;
---find total revenue is generated by each customer
select sum(f.sales_amount) as total_revenue,c.customer_id,(c.customer_firstname+ ' '+c.customer_lastname) as cust_name from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_id,(c.customer_firstname+' '+c.customer_lastname)
order by sum(f.sales_amount) desc ;
---what is the distribution of sold items across countries
select count(s.sales_quantity) as sold_items,c.country
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.country
order by count(s.sales_quantity) desc;

------------------------------------------------------------------Ranking analysis

--which 5 products generate the highest revenue
select top 5 p.product_name,sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by sum(f.sales_amount) desc;
---------------------------------------------window fn
select * from (
select  p.product_name,sum(f.sales_amount) as total_revenue,
ROW_NUMBER() over( order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name) t
where rank_products<=5 ;

----------------------------------------------------------------------------what are the 5 worst performing products in terms of sale
select top 5 p.product_name,sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by sum(f.sales_amount) ;

------------------------find top 10 cust who generated the highest revenue and 3 with fewest orders
select top 10 c.customer_key,c.customer_firstname+' '+c.customer_lastname as cust_name,sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key,c.customer_firstname+' '+c.customer_lastname
order by sum(f.sales_amount) desc;

select top 3 c.customer_key,c.customer_firstname+' '+c.customer_lastname as cust_name,count(distinct(order_number)) as total_orders
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.customer_firstname+' '+c.customer_lastname
order by total_orders;

-------------------analyze sales performance over time
select year(order_date) year_sales, sum(sales_amount) as total_sales,
count(distinct(customer_key)) as total_cust,
sum(sales_quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by year(order_date)
order by total_sales desc;

select year(order_date) year_sales,month(order_date) month_sales, sum(sales_amount) as total_sales,
count(distinct(customer_key)) as total_cust,
sum(sales_quantity) as total_quantity
from gold.fact_sales
where order_date is not null
group by month(order_date),year(order_date)
order by month(order_date);

-----------------------------------------------cumulative analysis

use datawarehouse;
select * from gold.fact_sales;

select MONTH(order_date) as emonth, sum(sales_amount) as totalsales
from gold.fact_sales
group by MONTH(order_date) order by emonth;

--------------------------running total(cummulative analysis)
select mon,totalsales,
sum(totalsales) over (partition by mon order by mon ) as runningtotal
from (
select DATETRUNC(month,order_date) as mon, sum(sales_amount) as totalsales
from gold.fact_sales
where order_date is not null
group by DATETRUNC(month,order_date)
)t;
-------------------------------year
select order_date,totalsales,
sum(totalsales) over ( order by order_date ) as runningtotal,
avg(avg_price) over(order by order_date) as runningavg
from (
select DATETRUNC(YEAR,order_date) as order_date, sum(sales_amount) as totalsales,
avg(sales_price) as avg_price
from gold.fact_sales
where order_date is not null
group by DATETRUNC(YEAR,order_date)
)t;

----------------------------------------performance analysis
---analyze the yearly performance  of products by comparing their sales to 
--both the avg sales performance of the product and the prev years sales--yoy analysis
with yearly_prds_sales as(

select p.product_name,
year(order_date) as order_year,
sum(s.sales_amount) as totalsales
from
gold.fact_sales s
left join
gold.dim_products p
on s.product_key=p.product_key
where order_date is not null
group by p.product_name,year(order_date)

)
select product_name,order_year,totalsales,
avg(totalsales) over(partition by product_name) avg_sales,
totalsales-avg(totalsales) over(partition by product_name)  as difference,
case when totalsales-avg(totalsales) over(partition by product_name) >0 then 'Above avg'
 when totalsales-avg(totalsales) over(partition by product_name) <0 then 'below avg'
else 'avg'
end as pv_status,
lag(totalsales) over (partition by product_name order by order_year) as prev_sales,
totalsales-lag(totalsales) over (partition by product_name order by order_year) as current_vs_prev_sales,
case when totalsales-lag(totalsales) over (partition by product_name order by order_year) >0 then 'Increase'
     when totalsales-lag(totalsales) over (partition by product_name order by order_year)<0 then 'Decrease'
else 'No change'
end as sales_status
from yearly_prds_sales
;

------------------part to whole analysis
-----which categories contribute the most to overall sales
with cte as(
select p.category,sum(f.sales_amount) as totalsales
from gold.fact_sales f
left join
gold.dim_products p
on f.product_key = p.product_key
group by p.category
)
select category,totalsales,
sum(totalsales) over() as overallsales,
concat(round((cast(totalsales as float)/sum(totalsales) over())*100,2),'%') as percent_sales
from cte;

-------------------------Data segmentation
--------measure by measure--segment products into cost ranges and count how many prod fall into that each segment
with product_range as 
(
select product_key,product_name,cost,
case when cost <100 then 'below 100'
     when cost between 100 and 500 then '100-500'
	 when cost between 500 and 1000 then '500-1000'
	 else 'above 100'
	 end as cost_range
from gold.dim_products)
select count(product_name) as product_list,cost_range 

from product_range
group by cost_range
order by cost_range;
------------------------------------------------------------------------------
--group cust into 3 segments based on their spending behaviour
----VIP: cust with atleast 12 months of history and spending more than 5000.
---Regular: customers atleast 12 months of his but spending 5000 or less
--New: customers with lifespan less than 12 months
with customer_segment as
(
select c.customer_key,sum(f.sales_amount)as total_spending ,
min(order_date) as first_order,
max(order_date) as last_order,
DATEDIFF(month,min(order_date), max(order_date)) as life_span
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key=f.customer_key
group by c.customer_key
)
select customer_seg,count(customer_key) as total_cust
from (
	select customer_key,
	case when life_span >= 12 and total_spending > 5000 then 'VIP'
	when life_span >= 12 and total_spending <= 5000 then 'Regular'
	else 'New' end as customer_seg

	from customer_segment
)t
group by customer_seg
order by count(customer_key) desc;

